server:
  port: 8086

spring:
  profiles:
    active: prod
  application:
    name: roombooking-dictionary

springdoc:
  swagger-ui:
    path: /api/v1/dicts/swagger-ui.html
  api-docs:
    path: /api/v1/dicts/api-docs
    groups:
      enabled: true