server:
  port: 8086

spring:
  data:
    mongodb:
      port: 27017
      database: dictionary
      host: localhost

springdoc:
  swagger-ui:
    path: /api/v1/dicts/swagger-ui.html
  api-docs:
    path: /api/v1/dicts/api-docs
    groups:
      enabled: true