version: "3"
services:
  mongoDocker:
    image: mongo:latest
    container_name: mongoDocker
    volumes:
      - /data/mongodb:/data/db
    networks:
      - booking-network
  roombooking-email:
    image: hcoin/roombooking-email:latest
    container_name: roombooking-email
    networks:
      - booking-network
  roombooking-payment:
    image: hcoin/roombooking-payment:latest
    container_name: roombooking-payment
    networks:
      - booking-network
  roombooking-dictionary:
    image: hcoin/roombooking-dictionary:latest
    container_name: roombooking-dictionary
    networks:
      - booking-network
  roombooking-app:
    image: hcoin/roombooking-app:latest
    container_name: roombooking-app
    networks:
      - booking-network
  gateway:
    image: hcoin/gateway:latest
    container_name: gateway
    ports:
      - 8080:8080
    networks:
      - booking-network

networks:
  booking-network:
    name: booking-network
    driver: bridge
