server:
  port: 9001

cloud:
  aws:
    region:
      static: ap-southeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
bookingBucket:
  name: bookingstorage
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error