server:
  port: 8087

cloud:
  aws:
    region:
      static: ap-southeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
bookingBucket:
  name: bookingstorage
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: roombooking-file

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

springdoc:
  swagger-ui:
    path: /api/v1/file/swagger.html
  api-docs:
    path: /api/v1/file/api-docs
    groups:
      enabled: true