server:
  port: 8085

spring:
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
  mail:
    host: smtp.gmail.com
    port: 587
    username: breaknotification@gmail.com
    password: jctebdtoijjfcanu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  swagger-ui:
    path: /api/v1/email/swagger-ui.html
  api-docs:
    path: /api/v1/email/api-docs
    groups:
      enabled: true