
spring:
  cloud:
    gateway:
      routes:
        - id: roombooking-app
          uri: http://roombooking-app:8081/
          predicates:
            - Path=/api/v1/app/**
        - id: roombooking-payment
          uri: http://roombooking-payment:8084/
          predicates:
            - Path=/api/v1/payment/**
        - id: roombooking-email
          uri: http://roombooking-email:8085/
          predicates:
            - Path=/api/v1/email/**
        - id: roombooking-dictionary
          uri: http://roombooking-dictionary:8086/
          predicates:
            - Path=/api/v1/dicts/**

logging:
  level:
    root: warn