server:
  port: 8080

spring:

  application:
    name: booking-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: booking-app
          uri: http://roombooking-app:8081/
          predicates:
            - Path=/api/v1/app/**
        - id: booking-payment
          uri: http://roombooking-payment:8084/
          predicates:
            - Path=/api/v1/payment/**
        - id: booking-email
          uri: http://roombooking-email:8085/
          predicates:
            - Path=/api/v1/email/**
        - id: booking-dictionary
          uri: http://roombooking-dictionary:8086/
          predicates:
            - Path=/api/v1/dicts/**

#      routes:
#        - id: booking-app
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/api/v1/app/**
#        - id: booking-payment
#          uri: http://localhost:8084/
#          predicates:
#            - Path=/api/v1/payment/**
#        - id: booking-email
#          uri: http://localhost:8085/
#          predicates:
#            - Path=/api/v1/email/**
#        - id: booking-dictionary
#          uri: http://localhost:8086/
#          predicates:
#            - Path=/api/v1/dicts/**
#  zipkin:
#    sender:
#      type: web
#    base-url: http://localhost:9411/
#  sleuth:
#    sampler:
#      probability: 1.0
logging:
  level:
    root: info
