server:
  port: 80

spring:
  profiles:
    active: dev
  application:
    name: roombooking-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedHeaders:
#              - content-type
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
