
spring:
  cloud:
    gateway:
      routes:
        - id: roombooking-app
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/app/**
        - id: roombooking-payment
          uri: http://localhost:8084/
          predicates:
            - Path=/api/v1/payment/**
        - id: roombooking-email
          uri: http://localhost:8085/
          predicates:
            - Path=/api/v1/email/**
        - id: roombooking-dictionary
          uri: http://localhost:8086/
          predicates:
            - Path=/api/v1/dicts/**
        - id: roombooking-file
          uri: http://roombooking-file:8087/
          predicates:
            - Path=/api/v1/file/**

logging:
  level:
    root: info
