
#host name is different when in production docker environment
bookingFeign:
  email-host-name: localhost
  payment-host-name: localhost

spring:
  data:
    mongodb:
      port: 27017
      database: roombooking
      host: localhost
#  zipkin:
#    sender:
#      type: web
#    base-url: http://localhost:9411/
#  sleuth:
#    sampler:
#      probability: 1.0
logging:
  level:
    root: info