
spring:
  data:
    mongodb:
      host: mongoDocker
      port: 27017
      database: roombooking
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        instance-id: ${spring.application.name}-01
        service-name: ${spring.application.name}
        port: ${server.port}
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      bookingEmailNotification: bookingEmailNotification
      bookingEmailReminder: bookingEmailReminder

logging:
  level:
    root: warn