
spring:
  data:
    mongodb:
      host: mongoDocker
      port: 27017
      database: roombooking
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: "thebreak-email"
    topics:
      bookingSuccess: bookingSuccess
      bookingReminder: bookingReminder
      bookingClose: bookingClose
      paymentSuccess: paymentSuccess

logging:
  level:
    root: warn