
spring:
  cloud:
    gateway:
      routes:
        - id: roombooking-app
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/app/**
        - id: roombooking-payment
          uri: http://localhost:8084/
          predicates:
            - Path=/api/v1/payment/**
        - id: roombooking-email
          uri: http://localhost:8085/
          predicates:
            - Path=/api/v1/email/**
        - id: roombooking-dictionary
          uri: http://localhost:8086/
          predicates:
            - Path=/api/v1/dicts/**

#  zipkin:
#    sender:
#      type: web
#    base-url: http://localhost:9411/
#  sleuth:
#    sampler:
#      probability: 1.0
logging:
  level:
    root: info
