spring:
  data:
    mongodb:
      port: 27017
      database: payment
      host: localhost
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      paymentSuccess: paymentSuccess


logging:
  level:
    root: info