
spring:
  #  zipkin:
#    sender:
#      type: web
#    base-url: http://localhost:9411/
#  sleuth:
#    sampler:
#      probability: 1.0
  data:
    mongodb:
      port: 27017
      database: payment
      host: localhost

logging:
  level:
    root: info