server:
  port: 8084

braintree:
  ENVIRONMENT: sandbox
  MERCHANT_ID: ${MERCHANT_ID}
  PUBLIC_KEY: ${PUBLIC_KEY}
  PRIVATE_KEY: ${PRIVATE_KEY}

spring:
  profiles:
    active: dev
  application:
    name: roombooking-payment

springdoc:
  swagger-ui:
    path: /api/v1/payment/swagger.html
  api-docs:
    path: /api/v1/payment/api-docs
    groups:
      enabled: true
