
spring:
  data:
    mongodb:
      port: 27017
      database: payment
      host: mongoDocker
  kafka:
    bootstrap-servers: kafka:9092
    topics:
      paymentSuccess: paymentSuccess

logging:
  level:
    root: warn