server:
  port: 8085

spring:
  application:
    name: roombooking-email
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        instance-id: ${spring.application.name}-01
        service-name: ${spring.application.name}
        port: ${server.port}
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      bookingEmailNotification: bookingEmailNotification
      bookingEmailReminder: bookingEmailReminder
    consumer:
      group-id: "thebreak-email"


  #  zipkin:
#    sender:
#      type: web
#    base-url: http://localhost:9411/
#  sleuth:
#    sampler:
#      probability: 1.0
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /api/v1/email/swagger.html
  api-docs:
    path: /api/v1/email/api-docs
    groups:
      enabled: true