server:
  port: 8085

spring:
  application:
    name: roombooking-email
  kafka:
    bootstrap-servers: localhost:9092  #need to change to localhost for local
    topics:
      bookingSuccess: bookingSuccess
      bookingReminder: bookingReminder
      bookingClose: bookingClose
      paymentSuccess: paymentSuccess
    consumer:
      group-id: "thebreak-email"



  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /api/v1/email/swagger.html
  api-docs:
    path: /api/v1/email/api-docs
    groups:
      enabled: true